const DEFAULT_PROMPT = "What would you like to ask?";

function createTalkBook({ intro, workAction, smallTalk, closing, prompt = DEFAULT_PROMPT }) {
  return {
    startNodeId: "intro",
    nodes: {
      intro: {
        type: "line",
        text: intro,
        next: "choice",
      },
      choice: {
        type: "choice",
        text: prompt,
        options: [
          { label: "Ask about work", next: "work" },
          { label: "Just chat", next: "chat" },
          { label: "Say goodbye", next: "end" },
        ],
      },
      work: {
        type: "action",
        text: workAction,
        next: "end",
      },
      chat: {
        type: "line",
        text: smallTalk,
        next: "end",
      },
      end: {
        type: "end",
        text: closing,
      },
    },
  };
}

export const roomKindLabels = {
  hall: "Hall",
  consultation: "Consultation",
  ward: "Ward",
  lab: "Lab",
  icu: "ICU",
  office: "Office",
  registration: "Registration",
  triage: "Triage",
  pharmacy: "Pharmacy",
  specialty_cluster_a: "Specialty Clinic A",
  specialty_cluster_b: "Specialty Clinic B",
  specialty_cluster_c: "Specialty Clinic C",
};

export const fixedNpcDefinitions = [
  {
    id: "hall-clerk",
    name: "Mara",
    roleLabel: "Clerk",
    floor: 1,
    roomKind: "hall",
    roomIndex: 0,
    placement: { x: 0.36, y: 0.52 },
    interactionRadius: 68,
    bodyColor: "#6d8fe8",
    headColor: "#f2d0bf",
    accentColor: "#7ac7ff",
    dialogueSetId: "hall-clerk",
  },
  {
    id: "consultation-doc",
    name: "Dr. Vale",
    roleLabel: "Doctor",
    floor: 1,
    roomKind: "consultation",
    roomIndex: 1,
    placement: { x: 0.54, y: 0.55 },
    interactionRadius: 68,
    bodyColor: "#8c7af0",
    headColor: "#f0cfbe",
    accentColor: "#c6b3ff",
    dialogueSetId: "consultation-doc",
  },
  {
    id: "ward-nurse",
    name: "Sera",
    roleLabel: "Nurse",
    floor: 1,
    roomKind: "ward",
    roomIndex: 0,
    placement: { x: 0.42, y: 0.55 },
    interactionRadius: 68,
    bodyColor: "#66bfa2",
    headColor: "#f4d1c4",
    accentColor: "#8ef0be",
    dialogueSetId: "ward-nurse",
  },
  {
    id: "icu-nurse",
    name: "Ivan",
    roleLabel: "Nurse",
    floor: 1,
    roomKind: "icu",
    roomIndex: 0,
    placement: { x: 0.58, y: 0.52 },
    interactionRadius: 68,
    bodyColor: "#d46d8e",
    headColor: "#f2ccb7",
    accentColor: "#ff9db2",
    dialogueSetId: "icu-nurse",
  },
  {
    id: "lab-tech",
    name: "Jun",
    roleLabel: "Lab Tech",
    floor: 1,
    roomKind: "lab",
    roomIndex: 0,
    placement: { x: 0.56, y: 0.48 },
    interactionRadius: 68,
    bodyColor: "#9b87f5",
    headColor: "#efcdb9",
    accentColor: "#b8a0ff",
    dialogueSetId: "lab-tech",
  },
  {
    id: "office-admin",
    name: "Nora",
    roleLabel: "Admin",
    floor: 1,
    roomKind: "office",
    roomIndex: 0,
    placement: { x: 0.48, y: 0.52 },
    interactionRadius: 68,
    bodyColor: "#e0b65b",
    headColor: "#f3d6be",
    accentColor: "#f4c96a",
    dialogueSetId: "office-admin",
  },
  {
    id: "family-medicine-guide",
    name: "Dr. Lin",
    roleLabel: "Family Medicine",
    floor: 1,
    roomKind: "specialty_cluster_a",
    roomIndex: 0,
    placement: { x: 0.18, y: 0.34 },
    interactionRadius: 68,
    bodyColor: "#6d8fe8",
    headColor: "#f2d0bf",
    accentColor: "#a8c9ff",
    dialogueSetId: "family-medicine-guide",
  },
  {
    id: "surgery-guide",
    name: "Dr. Qiao",
    roleLabel: "Surgery",
    floor: 1,
    roomKind: "specialty_cluster_a",
    roomIndex: 0,
    placement: { x: 0.5, y: 0.36 },
    interactionRadius: 68,
    bodyColor: "#d78464",
    headColor: "#f0cfbe",
    accentColor: "#f2b08f",
    dialogueSetId: "surgery-guide",
  },
  {
    id: "obgyn-guide",
    name: "Dr. Shen",
    roleLabel: "Obstetrics & Gynecology",
    floor: 1,
    roomKind: "specialty_cluster_a",
    roomIndex: 0,
    placement: { x: 0.82, y: 0.34 },
    interactionRadius: 68,
    bodyColor: "#d46d8e",
    headColor: "#f2ccb7",
    accentColor: "#ff9db2",
    dialogueSetId: "obgyn-guide",
  },
  {
    id: "pediatrics-guide",
    name: "Dr. You",
    roleLabel: "Pediatrics",
    floor: 1,
    roomKind: "specialty_cluster_a",
    roomIndex: 0,
    placement: { x: 0.28, y: 0.7 },
    interactionRadius: 68,
    bodyColor: "#76c59d",
    headColor: "#f4d1c4",
    accentColor: "#bdeccf",
    dialogueSetId: "pediatrics-guide",
  },
  {
    id: "ophthalmology-guide",
    name: "Dr. Xu",
    roleLabel: "Ophthalmology",
    floor: 1,
    roomKind: "specialty_cluster_a",
    roomIndex: 0,
    placement: { x: 0.72, y: 0.72 },
    interactionRadius: 68,
    bodyColor: "#9b87f5",
    headColor: "#efcdb9",
    accentColor: "#c9b9ff",
    dialogueSetId: "ophthalmology-guide",
  },
  {
    id: "ent-guide",
    name: "Dr. Han",
    roleLabel: "ENT",
    floor: 1,
    roomKind: "specialty_cluster_b",
    roomIndex: 0,
    placement: { x: 0.2, y: 0.34 },
    interactionRadius: 68,
    bodyColor: "#5aa0a8",
    headColor: "#f2d0bf",
    accentColor: "#98e0e5",
    dialogueSetId: "ent-guide",
  },
  {
    id: "dentistry-guide",
    name: "Dr. Rong",
    roleLabel: "Dentistry",
    floor: 1,
    roomKind: "specialty_cluster_b",
    roomIndex: 0,
    placement: { x: 0.5, y: 0.36 },
    interactionRadius: 68,
    bodyColor: "#d7aa60",
    headColor: "#f4d5bf",
    accentColor: "#f4d28d",
    dialogueSetId: "dentistry-guide",
  },
  {
    id: "dermatology-guide",
    name: "Dr. Mo",
    roleLabel: "Dermatology",
    floor: 1,
    roomKind: "specialty_cluster_b",
    roomIndex: 0,
    placement: { x: 0.82, y: 0.34 },
    interactionRadius: 68,
    bodyColor: "#84b56b",
    headColor: "#f2ccb7",
    accentColor: "#c8e8b2",
    dialogueSetId: "dermatology-guide",
  },
  {
    id: "psychiatry-guide",
    name: "Dr. Fei",
    roleLabel: "Psychiatry",
    floor: 1,
    roomKind: "specialty_cluster_b",
    roomIndex: 0,
    placement: { x: 0.28, y: 0.7 },
    interactionRadius: 68,
    bodyColor: "#8c7af0",
    headColor: "#f0cfbe",
    accentColor: "#c6b3ff",
    dialogueSetId: "psychiatry-guide",
  },
  {
    id: "rehab-guide",
    name: "Dr. Bei",
    roleLabel: "Rehabilitation",
    floor: 1,
    roomKind: "specialty_cluster_b",
    roomIndex: 0,
    placement: { x: 0.72, y: 0.72 },
    interactionRadius: 68,
    bodyColor: "#66bfa2",
    headColor: "#f3d6be",
    accentColor: "#8ef0be",
    dialogueSetId: "rehab-guide",
  },
  {
    id: "pain-guide",
    name: "Dr. Zhen",
    roleLabel: "Pain Clinic",
    floor: 1,
    roomKind: "specialty_cluster_c",
    roomIndex: 0,
    placement: { x: 0.26, y: 0.42 },
    interactionRadius: 68,
    bodyColor: "#c97a68",
    headColor: "#f2ccb7",
    accentColor: "#efb1a3",
    dialogueSetId: "pain-guide",
  },
  {
    id: "specialty-triage-guide",
    name: "Mina",
    roleLabel: "Specialty Navigation",
    floor: 1,
    roomKind: "specialty_cluster_c",
    roomIndex: 0,
    placement: { x: 0.52, y: 0.52 },
    interactionRadius: 68,
    bodyColor: "#6ba7d8",
    headColor: "#f2d0bf",
    accentColor: "#b5dcff",
    dialogueSetId: "specialty-triage-guide",
  },
  {
    id: "wellness-desk-guide",
    name: "Aster",
    roleLabel: "Follow-up Desk",
    floor: 1,
    roomKind: "specialty_cluster_c",
    roomIndex: 0,
    placement: { x: 0.78, y: 0.42 },
    interactionRadius: 68,
    bodyColor: "#9bb36d",
    headColor: "#efcdb9",
    accentColor: "#d6ebaf",
    dialogueSetId: "wellness-desk-guide",
  },
];

export const fixedNpcDialogueBooks = {
  "hall-clerk": createTalkBook({
    intro: "Morning. Keep to the right if you are only passing through.",
    workAction: "Mara taps the clipboard once. \"Forms first, then the rest of the day.\"",
    smallTalk: "Some days the lobby feels like a river. Your job is to keep your balance.",
    closing: "Come back if you need directions, or a quiet place to stand for a second.",
  }),
  "consultation-doc": createTalkBook({
    intro: "The consultation rooms are at their best when the hallway stops arguing with itself.",
    workAction: "Dr. Vale points toward the next room. \"Keep your notes short. Clarity saves time.\"",
    smallTalk: "If you bring in good questions, the answers usually show up on time.",
    closing: "Take it easy. Calm hands make better charts.",
  }),
  "ward-nurse": createTalkBook({
    intro: "Ward shifts are mostly small things done well.",
    workAction: "Sera checks the clipboard. \"Water, pillows, and patience. In that order.\"",
    smallTalk: "The quiet here is not empty. It is just busy in a softer way.",
    closing: "If you need me, I am usually one room away.",
  }),
  "icu-nurse": createTalkBook({
    intro: "The ICU keeps its own pace. We just keep up with it.",
    workAction: "Ivan lowers his voice. \"Short sentences. Clear notes. No wasted motion.\"",
    smallTalk: "The best part of a calm shift is noticing it after it happens.",
    closing: "Stay steady. That helps more than people think.",
  }),
  "lab-tech": createTalkBook({
    intro: "If it glows, be gentle. If it hums, label it.",
    workAction: "Jun nudges a tray of samples. \"Everything belongs somewhere. The trick is remembering where.\"",
    smallTalk: "Machines can be picky, but they are honest.",
    closing: "Bring clean notes next time. They save everyone's afternoon.",
  }),
  "office-admin": createTalkBook({
    intro: "The office runs on lists, labels, and one stubborn kettle.",
    workAction: "Nora slides a stack of papers back into order. \"A tidy desk is a kinder desk.\"",
    smallTalk: "Some days are made of paperwork. Others are made of tiny victories.",
    closing: "If you do not know where to go, the office usually does.",
  }),
  "family-medicine-guide": createTalkBook({
    intro: "Family medicine is the safest first stop when symptoms are vague, mild, or spread across more than one system.",
    workAction: "Dr. Lin taps the department board. \"Unclear symptoms, first visits, and light issues all land here before we split them out.\"",
    smallTalk: "Patients who say 'I just feel unwell' usually start with us, and that is exactly what we are for.",
    closing: "If you are not sure which specialty fits, family medicine can keep the day moving.",
  }),
  "surgery-guide": createTalkBook({
    intro: "Surgery covers wounds, trauma, lumps, and pain that feels local and urgent.",
    workAction: "Dr. Qiao adjusts a dressing tray. \"Cuts, swelling, sudden one-point pain, and post-injury checks all belong here.\"",
    smallTalk: "A sharp story helps. Tell us when it started, what happened, and whether movement makes it worse.",
    closing: "If the problem sounds mechanical, visible, or injury-related, surgery is usually the right door.",
  }),
  "obgyn-guide": createTalkBook({
    intro: "Obstetrics and gynecology handles gynecologic symptoms, menstrual problems, and pregnancy-related concerns.",
    workAction: "Dr. Shen gestures to the consultation seats. \"Lower abdominal pain, abnormal bleeding, discharge, and pregnancy follow-up all route here.\"",
    smallTalk: "A calm, private conversation usually answers half the anxiety before the exam even begins.",
    closing: "If the symptom is clearly tied to pregnancy or gynecologic history, come straight here.",
  }),
  "pediatrics-guide": createTalkBook({
    intro: "Children with fever, cough, vomiting, or diarrhea should usually be seen in pediatrics first.",
    workAction: "Dr. You smiles toward the waiting chairs. \"Kids are not small adults. Even common symptoms need their own pacing and questions.\"",
    smallTalk: "Parents who remember appetite, sleep, and bathroom changes save us a lot of guesswork.",
    closing: "If the patient is a child, pediatrics is usually the cleanest route.",
  }),
  "ophthalmology-guide": createTalkBook({
    intro: "Red eyes, eye pain, blurred vision, and sudden visual changes belong in ophthalmology.",
    workAction: "Dr. Xu points at the eye chart. \"If the symptom is in the eye itself or in vision, do not leave it floating between departments.\"",
    smallTalk: "People wait too long with eye symptoms because they hope rest will fix them. Sometimes that is not a good gamble.",
    closing: "Vision complaints deserve their own lane, and that lane is here.",
  }),
  "ent-guide": createTalkBook({
    intro: "ENT covers sore throat, blocked nose, sinus pressure, ear pain, and voice changes.",
    workAction: "Dr. Han checks a scope light. \"If it is nose, throat, or ear territory, we can usually sort it quickly.\"",
    smallTalk: "Patients often say 'just a cold,' but the pattern matters more than the label.",
    closing: "For airway-adjacent discomfort that is not obviously chest or dental, ENT is a strong match.",
  }),
  "dentistry-guide": createTalkBook({
    intro: "Dentistry handles tooth pain, gum bleeding, oral ulcers, and pain that worsens with chewing.",
    workAction: "Dr. Rong lines up instruments. \"If the pain bites back when you eat, smile, or tap the tooth, it usually belongs here.\"",
    smallTalk: "Mouth pain has a way of taking over a whole day out of proportion to its size.",
    closing: "Oral pain should not get lost inside general medicine if the tooth or gum is clearly the source.",
  }),
  "dermatology-guide": createTalkBook({
    intro: "Dermatology is for rash, itch, allergy patterns, and skin changes that patients can actually point at.",
    workAction: "Dr. Mo looks over a skin chart. \"Color, border, spread, and timing matter. If the skin changed first, start here.\"",
    smallTalk: "The symptom may be visible, but the trigger is often hiding in habits, food, medicine, or weather.",
    closing: "If the complaint lives on the skin, dermatology gives it the attention it deserves.",
  }),
  "psychiatry-guide": createTalkBook({
    intro: "Psychiatry supports anxiety, insomnia, low mood, panic, and distress that feels emotional, cognitive, or behavioral.",
    workAction: "Dr. Fei lowers the room volume. \"When the main symptom is fear, sleeplessness, or mood collapse, the route should reflect that honestly.\"",
    smallTalk: "Patients often apologize for psychiatric symptoms as if suffering needs a better excuse. It does not.",
    closing: "When emotional burden is the center of the story, psychiatry is not a fallback. It is the right place.",
  }),
  "rehab-guide": createTalkBook({
    intro: "Rehabilitation medicine fits post-op recovery, mobility loss, chronic weakness, and training after injury.",
    workAction: "Dr. Bei rolls a shoulder model across the desk. \"Recovery is not just rest. It is guided function, repetition, and safe progression.\"",
    smallTalk: "A lot of patients only realize they need rehab when daily motion starts negotiating with them.",
    closing: "If the issue is movement, function, or getting strength back, rehab is the better frame.",
  }),
  "pain-guide": createTalkBook({
    intro: "Pain clinic covers chronic pain, nerve pain, and neck-shoulder-back-leg pain that lingers or keeps returning.",
    workAction: "Dr. Zhen traces a line along a spine chart. \"When pain becomes the main disease instead of just a clue, we handle it here.\"",
    smallTalk: "Persistent pain changes posture, sleep, patience, and mood long before scans explain everything.",
    closing: "If the whole visit is about managing pain itself, this clinic makes the most sense.",
  }),
  "specialty-triage-guide": createTalkBook({
    intro: "This specialty navigation desk helps route uncertain cases into the right outpatient lane.",
    workAction: "Mina points to three themed clinic zones. \"Cluster A handles first-visit and broad specialty intake, Cluster B handles sensory and chronic specialties, Cluster C catches pain and follow-up navigation.\"",
    smallTalk: "Even a strong front desk still needs somewhere to send the patients who say, 'I am not sure what this is.'",
    closing: "If the symptom story is fuzzy, start with the navigation desk and narrow from there.",
  }),
  "wellness-desk-guide": createTalkBook({
    intro: "The follow-up desk helps patients after a first consultation: education, referral directions, and next-step reminders.",
    workAction: "Aster flips to a color-coded checklist. \"Not every visit ends with medicine. Some end with rehab, reassessment, or better instructions.\"",
    smallTalk: "Good follow-up is less dramatic than emergency care, but it prevents a lot of repeat confusion.",
    closing: "When the next step matters more than the first step, this desk keeps patients from drifting.",
  }),
};
